version: '3.7'

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nextcloud_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - /srv/docker/.env-files/nextcloud_db.env
    networks:
      - nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    command: redis-server --requirepass mgd1zxbkOWTfuPISXoEJ
    restart: always
    networks:
      - nextcloud

  nextcloud_app:
    image: nextcloud:stable
    restart: always
    container_name: nextcloud_app
    volumes:
      - nextcloud_app:/var/www/html
    env_file:
      - /srv/docker/.env-files/nextcloud_app.env
    labels:
      - "traefik.docker.network=docker_proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`drive.jockelnode.de`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect"
      - "traefik.http.middlewares.nextcloud.headers.sslredirect=true"
      - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' jockelnode.de *.jockelnode.de"
      - "traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011"
      - "traefik.http.routers.nextcloud.tls.options=default"
      - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloud.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=https://$${1}/remote.php/dav/"
    depends_on:
      - nextcloud_db
      - redis
    networks:
      - docker_proxy
      - nextcloud

  cron:
    image: nextcloud:stable
    restart: always
    container_name: nextcloud_cron
    volumes:
      - nextcloud_app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - redis
    networks:
      - nextcloud


volumes:
  nextcloud_db:
    driver: local
  nextcloud_app:
    driver: local

networks:
  docker_proxy:
    external: true
  nextcloud:
